[env.production]
name = "mirror"
minify = true
workers_dev = false

[env.production.vars]
NAME = "mirror"
VERSION = "1.0.0"
MODE = "production"

[env.production.vars.SECURE_CONFIG]
AllowMainSiteHTML = 0
AllowSubDomainHTML = 1
EnableMainSite = 1
MainSiteDomain = ["*"]
EnableSubDomain = 1
SubKeyList = []