# Production environment

[env.production]
name = "mirror"
minify = true
workers_dev = false

[env.production.vars]
NAME = "mirror"
VERSION = "1.0.0"
MODE = "production"

[env.production.vars.SECURE_CONFIG]

# Allow responsing HTML for main domain
AllowMainSiteHTML = 0
# Allow responsing HTML for sub domain
AllowSubDomainHTML = 1

# Expose to main domain
EnableMainSite = 1
MainSiteDomain = [
    # type * to match all domain
    "example.com" # example.com is allowed
]

# Expose to sub domain
EnableSubDomain = 1
SubKeyList = [
    "abcde" # abcde.example.com is allowed
]